#!/bin/env python3
#
# Copyright OpenEmbedded Contributors
#
# SPDX-License-Identifier: MIT
#

import os
import unittest
import json
import shutil
import subprocess

current_path = os.path.abspath(__file__)[:-len(os.path.basename(__file__))]
test_data_path = os.path.join(current_path, "tests")
cve_summary_from_vex_class = os.path.join(test_data_path, "cve-binutils-summary-vexclass.json")
cve_summary_with_issue = os.path.join(test_data_path, "cve-binutils-summary-with-issues.json")
raw_db_path = os.path.join(test_data_path, "raw-cve-db_binutils-focus")

data_path = "testdata"
cve_generated_path = os.path.join(data_path, "cve-summary.json")
vex_generated_path = os.path.join(data_path, "vex-summary.json")

scan_tool = os.path.join(
        current_path, "yocto-vex-check.py"
    )

class TestCase(unittest.TestCase):
    @classmethod
    def setUpClass(self):
        self.vex_command = [scan_tool, "vex", "-d", data_path, "-fc", cve_summary_with_issue]
        self.cve_command = [scan_tool, "cve", "-d", data_path, "-fc", cve_summary_from_vex_class, "-fv", vex_generated_path, "-db-type", "CVE", "-db", raw_db_path]

    def test_command(self):
        output = subprocess.run(
            self.vex_command,
            capture_output=True,
            text=True,
        )
        self.assertEqual(output.returncode, 0)

        output = subprocess.run(
            self.cve_command,
            capture_output=True,
            text=True,
        )
        self.assertEqual(output.returncode, 0)

    def test_compare_cves(self):
        cve_build = {}
        cve_generated = {}

        with open(cve_summary_with_issue, "r") as build_file:
            cve_build = json.load(build_file)

        with open(cve_generated_path, "r") as file:
            cve_generated = json.load(file)

        cves_from_build = list(
            set(sorted([i["id"] for p in cve_build["package"] for i in p["issue"]]))
        )
        cves_generated = list(
            set(sorted([i["id"] for p in cve_generated["package"] for i in p["issue"]]))
        )

        self.assertEqual(
            len(cves_from_build),
            len(cves_generated),
            msg="Number of CVE generated from standalone tool does not equal the number of CVE found from original build.",
        )

        self.assertEqual(
            cves_from_build,
            cves_generated,
            msg="CVE found from build differs from those generated by standalone tool",
        )

    def test_status(self):
        with open(cve_summary_with_issue, "r") as build_file:
            cve_build = json.load(build_file)

        with open(cve_generated_path, "r") as file:
            cve_generated = json.load(file)

        cves_from_build = sorted(cve_build["package"][0]["issue"], key=lambda d: d['id'])
        cves_generated = sorted(cve_generated["package"][0]["issue"], key=lambda d: d['id'])

        for i in range(len(cves_from_build)):
            self.assertEqual(
                cves_from_build[i]["id"],
                cves_generated[i]["id"],
                msg="CVEs from build and CVEs generated from tool differs"
            )
            self.assertEqual(
                cves_from_build[i]["status"],
                cves_generated[i]["status"],
                msg="CVE status found from build differs from those generated by standalone tool",
            )
            self.assertEqual(
                cves_from_build[i]["detail"],
                cves_generated[i]["detail"],
                msg="CVE detail found from build differs from those generated by standalone tool",
            )

    def test_compare_cve_vex(self):
        cve_build = {}
        cve_generated = {}
        vex = {}

        with open(cve_summary_with_issue, "r") as build_file:
            cve_build = json.load(build_file)

        with open(cve_generated_path, "r") as file:
            cve_generated = json.load(file)

        with open(vex_generated_path, "r") as file:
            vex = json.load(file)

        cves_from_build = list(
            set(sorted([i["id"] for p in cve_build["package"] for i in p["issue"]]))
        )
        cves_generated = list(
            set(sorted([i["id"] for p in cve_generated["package"] for i in p["issue"]]))
        )
        vexs = list(set(sorted([k for k in vex.keys()])))

        self.assertEqual(
            len(cves_from_build),
            len(vexs),
            msg="Number of CVE found from build differs from CVE gathered in VEX summary",
        )

        self.assertEqual(
            len(cves_generated),
            len(vexs),
            msg="Number of CVE found from standalone tool differs from CVE gathered in VEX summary",
        )

        self.assertEqual(
            cves_from_build,
            vexs,
            msg="CVEs found from build differs from CVE gathered in VEX summary",
        )

        self.assertEqual(
            cves_generated,
            vexs,
            msg="CVEs found from standalone tool differs from CVE gathered in VEX summary",
        )

    @classmethod
    def tearDownClass(self):
        shutil.rmtree(data_path, ignore_errors=True)

if __name__ == "__main__":
    unittest.main()
