#!/bin/env python3
#
# Copyright OpenEmbedded Contributors
#
# SPDX-License-Identifier: MIT
#

import os, sys
import unittest
import pytest
import json
from parameterized import parameterized


class TestCase(unittest.TestCase):
    data_path = "testdata"
    cve_path = os.path.join(data_path, "cve-summary.json")
    cve_path_from_build = (
        "/".join(os.path.abspath(__file__).split("/")[:-1])
        + "/tests/cve-summary-from-build.json"
    )
    vex_path = os.path.join(data_path, "vex-summary.json")

    def test_compare_cves(self):
        cve_build = {}
        cve_generated = {}

        with open(self.cve_path_from_build, "r") as build_file:
            cve_build = json.load(build_file)

        with open(self.cve_path, "r") as file:
            cve_generated = json.load(file)

        cves_from_build = list(
            set(sorted([i["id"] for p in cve_build["package"] for i in p["issue"]]))
        )
        cves_generated = list(
            set(sorted([i["id"] for p in cve_generated["package"] for i in p["issue"]]))
        )

        self.assertEqual(
            len(cves_from_build),
            len(cves_generated),
            msg="Number of CVE generated from standalone tool does not equal the number of CVE found from original build.",
        )

        self.assertEqual(
            cves_from_build,
            cves_generated,
            msg="CVE found from build differes from those generated by standalone tool",
        )

    def test_compare_cve_vex(self):
        cve_build = {}
        cve_generated = {}
        vex = {}

        with open(self.cve_path_from_build, "r") as build_file:
            cve_build = json.load(build_file)

        with open(self.cve_path, "r") as file:
            cve_generated = json.load(file)

        with open(self.vex_path, "r") as file:
            vex = json.load(file)

        cves_from_build = list(
            set(sorted([i["id"] for p in cve_build["package"] for i in p["issue"]]))
        )
        cves_generated = list(
            set(sorted([i["id"] for p in cve_generated["package"] for i in p["issue"]]))
        )
        vexs = list(set(sorted([k for k in vex.keys()])))

        self.assertEqual(
            len(cves_from_build),
            len(vexs),
            msg="Number of CVE found from build differes from CVE gathered in VEX summary",
        )

        self.assertEqual(
            len(cves_generated),
            len(vexs),
            msg="Number of CVE found from standalone tool differes from CVE gathered in VEX summary",
        )

        self.assertEqual(
            cves_from_build,
            vexs,
            msg="CVEs found from build differes from CVE gathered in VEX summary",
        )

        self.assertEqual(
            cves_generated,
            vexs,
            msg="CVEs found from standalone tool differes from CVE gathered in VEX summary",
        )
